apiVersion: v1
data:
  common.conf: |+
    FQDNLookup false
    Interval 60

  sensors.conf: |
    LoadPlugin sensors

  influx.conf: |+
    LoadPlugin network
    <Plugin network>
    Server "INFLUXDB_HOST" "25826"
    </Plugin>

  prometheus.conf: |+
    LoadPlugin write_prometheus
    <Plugin "write_prometheus">
      Port "9103"
    </Plugin>

  hostname.conf: |+
    Include "/tmp/collectd-hostname"

  smart-nvme.conf: |+
    LoadPlugin exec
    <Plugin exec>
      Exec "nvme-sensors:nvme-sensors" "/opt/smart-nvme.sh"
    </Plugin>

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: collectd-config-include
